// src/license/keys.js
//
// Ghost Architect Ed25519 public key for license signature verification.
//
// This is the PUBLIC half of the keypair. It's safe to ship in the binary —
// the private signing key lives only on EJ's iMac at ~/.ghost-signing/private.pem
// and never touches any repo, backup-to-cloud, or distribution channel.
//
// If this key needs to be rotated, every active license becomes unverifiable
// at the moment of rotation. Don't rotate without a migration plan.
//
// Generated by scripts/generate-keypair.mjs on 2026-05-15.

import crypto from 'crypto';

// 32-byte raw Ed25519 public key as hex.
const PUBLIC_KEY_HEX = '26db0bf434e3f6407653514ad10a29016f4e4da302de0c144a1a448127c9b1ac';

// Wrap the raw 32 bytes back into DER SPKI for Node's crypto.verify().
// Ed25519 SPKI prefix (12 bytes) + 32-byte raw key = 44-byte DER blob.
const ED25519_SPKI_PREFIX = Buffer.from([
  0x30, 0x2a,                    // SEQUENCE, length 42
  0x30, 0x05,                    // SEQUENCE, length 5
  0x06, 0x03, 0x2b, 0x65, 0x70,  // OID 1.3.101.112 (Ed25519)
  0x03, 0x21, 0x00,              // BIT STRING, length 33, 0 unused bits
]);

function buildPublicKeyObject() {
  const raw = Buffer.from(PUBLIC_KEY_HEX, 'hex');
  if (raw.length !== 32) {
    throw new Error(`Ghost license public key must be 32 bytes, got ${raw.length}`);
  }
  const spki = Buffer.concat([ED25519_SPKI_PREFIX, raw]);
  return crypto.createPublicKey({ key: spki, format: 'der', type: 'spki' });
}

// Lazy + memoized so test environments can mock if needed without paying
// the cost on every import.
let cached = null;
export function getPublicKey() {
  if (!cached) cached = buildPublicKeyObject();
  return cached;
}

export function getPublicKeyHex() {
  return PUBLIC_KEY_HEX;
}
